### ISSUE TITLE
[Question] Compile output

### ISSUE THREAD

**Issue by MarieUwU-nerd** [Hadi999/NXcrypt#4]
Is it possible to compile the py output to exe ?

**Comment by Hadi999** [comment]
Yes , with Py2exe or cx_Freeze .

https://stackoverflow.com/questions/10592913/how-do-i-convert-a-python-program-to-a-runnable-exe-windows-program

http://www.py2exe.org/

https://anthony-tuininga.github.io/cx_Freeze/
